/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_libalf_jni_LibALFObject */

#ifndef _Included_de_libalf_jni_LibALFObject
#define _Included_de_libalf_jni_LibALFObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_libalf_jni_LibALFObject
 * Method:    getLibALFVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_libalf_jni_LibALFObject_getLibALFVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
