/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_libalf_jni_AlgorithmRPNI */

#ifndef _Included_de_libalf_jni_AlgorithmRPNI
#define _Included_de_libalf_jni_AlgorithmRPNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_libalf_jni_AlgorithmRPNI
 * Method:    init
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_de_libalf_jni_AlgorithmRPNI_init__JI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     de_libalf_jni_AlgorithmRPNI
 * Method:    init
 * Signature: (JIJ)J
 */
JNIEXPORT jlong JNICALL Java_de_libalf_jni_AlgorithmRPNI_init__JIJ
  (JNIEnv *, jobject, jlong, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
