/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_libalf_jni_AlgorithmBiermannMiniSAT */

#ifndef _Included_de_libalf_jni_AlgorithmBiermannMiniSAT
#define _Included_de_libalf_jni_AlgorithmBiermannMiniSAT
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_libalf_jni_AlgorithmBiermannMiniSAT
 * Method:    init
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_de_libalf_jni_AlgorithmBiermannMiniSAT_init
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
