/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_libalf_jni_RandomGenerator */

#ifndef _Included_de_libalf_jni_RandomGenerator
#define _Included_de_libalf_jni_RandomGenerator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_libalf_jni_RandomGenerator
 * Method:    createRandomDFA
 * Signature: (II)Lde/libalf/jni/BasicAutomaton;
 */
JNIEXPORT jobject JNICALL Java_de_libalf_jni_RandomGenerator_createRandomDFA
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_libalf_jni_RandomGenerator
 * Method:    discardTables
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_libalf_jni_RandomGenerator_discardTables
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
