/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_libalf_jni_Knowledgebase */

#ifndef _Included_de_libalf_jni_Knowledgebase
#define _Included_de_libalf_jni_Knowledgebase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_libalf_jni_Knowledgebase
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_libalf_jni_Knowledgebase_init
  (JNIEnv *, jobject);

/*
 * Class:     de_libalf_jni_Knowledgebase
 * Method:    is_answered
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_de_libalf_jni_Knowledgebase_is_1answered
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_libalf_jni_Knowledgebase
 * Method:    is_empty
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_de_libalf_jni_Knowledgebase_is_1empty
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_libalf_jni_Knowledgebase
 * Method:    count_queries
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_libalf_jni_Knowledgebase_count_1queries
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_libalf_jni_Knowledgebase
 * Method:    getQueries
 * Signature: (I)Lde/libalf/jni/Queries;
 */
JNIEXPORT jobject JNICALL Java_de_libalf_jni_Knowledgebase_getQueries
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_libalf_jni_Knowledgebase
 * Method:    resolve_query
 * Signature: ([IZI)Z
 */
JNIEXPORT jboolean JNICALL Java_de_libalf_jni_Knowledgebase_resolve_1query
  (JNIEnv *, jobject, jintArray, jboolean, jint);

/*
 * Class:     de_libalf_jni_Knowledgebase
 * Method:    add_knowledge
 * Signature: ([IZI)Z
 */
JNIEXPORT jboolean JNICALL Java_de_libalf_jni_Knowledgebase_add_1knowledge
  (JNIEnv *, jobject, jintArray, jboolean, jint);

/*
 * Class:     de_libalf_jni_Knowledgebase
 * Method:    clear
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_libalf_jni_Knowledgebase_clear
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_libalf_jni_Knowledgebase
 * Method:    clear_queries
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_libalf_jni_Knowledgebase_clear_1queries
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_libalf_jni_Knowledgebase
 * Method:    undo
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_de_libalf_jni_Knowledgebase_undo
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     de_libalf_jni_Knowledgebase
 * Method:    get_memory_usage
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_libalf_jni_Knowledgebase_get_1memory_1usage
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_libalf_jni_Knowledgebase
 * Method:    get_timestamp
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_libalf_jni_Knowledgebase_get_1timestamp
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_libalf_jni_Knowledgebase
 * Method:    count_answers
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_libalf_jni_Knowledgebase_count_1answers
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
