/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_libalf_jni_QueryIterator */

#ifndef _Included_de_libalf_jni_QueryIterator
#define _Included_de_libalf_jni_QueryIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_libalf_jni_QueryIterator
 * Method:    init
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_libalf_jni_QueryIterator_init
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_libalf_jni_QueryIterator
 * Method:    nextQuery
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_de_libalf_jni_QueryIterator_nextQuery
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_libalf_jni_QueryIterator
 * Method:    answer
 * Signature: (ZJ)Z
 */
JNIEXPORT jboolean JNICALL Java_de_libalf_jni_QueryIterator_answer
  (JNIEnv *, jobject, jboolean, jlong);

#ifdef __cplusplus
}
#endif
#endif
