/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_libalf_jni_AlgorithmAngluin */

#ifndef _Included_de_libalf_jni_AlgorithmAngluin
#define _Included_de_libalf_jni_AlgorithmAngluin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_libalf_jni_AlgorithmAngluin
 * Method:    init
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_de_libalf_jni_AlgorithmAngluin_init
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
