/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AlgorithmAngluin */

#ifndef _Included_AlgorithmAngluin
#define _Included_AlgorithmAngluin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AlgorithmAngluin
 * Method:    init
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_AlgorithmAngluin_init
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     AlgorithmAngluin
 * Method:    add_counterexample
 * Signature: ([II)V
 */
JNIEXPORT void JNICALL Java_AlgorithmAngluin_add_1counterexample
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     AlgorithmAngluin
 * Method:    advance
 * Signature: (I)LLibALFAutomaton;
 */
JNIEXPORT jobject JNICALL Java_AlgorithmAngluin_advance
  (JNIEnv *, jobject, jint);

/*
 * Class:     AlgorithmAngluin
 * Method:    conjecture_ready
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_AlgorithmAngluin_conjecture_1ready
  (JNIEnv *, jobject, jint);

/*
 * Class:     AlgorithmAngluin
 * Method:    get_alphabet_size
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_AlgorithmAngluin_get_1alphabet_1size
  (JNIEnv *, jobject, jint);

/*
 * Class:     AlgorithmAngluin
 * Method:    increase_alphabet_size
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_AlgorithmAngluin_increase_1alphabet_1size
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     AlgorithmAngluin
 * Method:    set_alphabet_size
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_AlgorithmAngluin_set_1alphabet_1size
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     AlgorithmAngluin
 * Method:    set_knowledge_source
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_AlgorithmAngluin_set_1knowledge_1source
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     AlgorithmAngluin
 * Method:    set_knowledge_source_NULL
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_AlgorithmAngluin_set_1knowledge_1source_1NULL
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
