/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_libalf_jni_JNIAlgorithmDeterministicInferringCSPMinisat */

#ifndef _Included_de_libalf_jni_JNIAlgorithmDeterministicInferringCSPMinisat
#define _Included_de_libalf_jni_JNIAlgorithmDeterministicInferringCSPMinisat
#ifdef __cplusplus
extern "C" {
#endif
#undef de_libalf_jni_JNIAlgorithmDeterministicInferringCSPMinisat_serialVersionUID
#define de_libalf_jni_JNIAlgorithmDeterministicInferringCSPMinisat_serialVersionUID 1LL
#undef de_libalf_jni_JNIAlgorithmDeterministicInferringCSPMinisat_serialVersionUID
#define de_libalf_jni_JNIAlgorithmDeterministicInferringCSPMinisat_serialVersionUID 2LL
#undef de_libalf_jni_JNIAlgorithmDeterministicInferringCSPMinisat_serialVersionUID
#define de_libalf_jni_JNIAlgorithmDeterministicInferringCSPMinisat_serialVersionUID 2LL
/*
 * Class:     de_libalf_jni_JNIAlgorithmDeterministicInferringCSPMinisat
 * Method:    init
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_de_libalf_jni_JNIAlgorithmDeterministicInferringCSPMinisat_init__JJI
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     de_libalf_jni_JNIAlgorithmDeterministicInferringCSPMinisat
 * Method:    init
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_de_libalf_jni_JNIAlgorithmDeterministicInferringCSPMinisat_init__JI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     de_libalf_jni_JNIAlgorithmDeterministicInferringCSPMinisat
 * Method:    init
 * Signature: (JJIZ)J
 */
JNIEXPORT jlong JNICALL Java_de_libalf_jni_JNIAlgorithmDeterministicInferringCSPMinisat_init__JJIZ
  (JNIEnv *, jobject, jlong, jlong, jint, jboolean);

/*
 * Class:     de_libalf_jni_JNIAlgorithmDeterministicInferringCSPMinisat
 * Method:    init
 * Signature: (JIZ)J
 */
JNIEXPORT jlong JNICALL Java_de_libalf_jni_JNIAlgorithmDeterministicInferringCSPMinisat_init__JIZ
  (JNIEnv *, jobject, jlong, jint, jboolean);

/*
 * Class:     de_libalf_jni_JNIAlgorithmDeterministicInferringCSPMinisat
 * Method:    uses_unary_encoding
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_de_libalf_jni_JNIAlgorithmDeterministicInferringCSPMinisat_uses_1unary_1encoding
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_libalf_jni_JNIAlgorithmDeterministicInferringCSPMinisat
 * Method:    set_unary_encoding
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_de_libalf_jni_JNIAlgorithmDeterministicInferringCSPMinisat_set_1unary_1encoding
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     de_libalf_jni_JNIAlgorithmDeterministicInferringCSPMinisat
 * Method:    is_logging_model
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_de_libalf_jni_JNIAlgorithmDeterministicInferringCSPMinisat_is_1logging_1model
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_libalf_jni_JNIAlgorithmDeterministicInferringCSPMinisat
 * Method:    set_log_model
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_de_libalf_jni_JNIAlgorithmDeterministicInferringCSPMinisat_set_1log_1model
  (JNIEnv *, jobject, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
