/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_libalf_jni_JNIAlgorithmDFAInferringMinisat */

#ifndef _Included_de_libalf_jni_JNIAlgorithmDFAInferringMinisat
#define _Included_de_libalf_jni_JNIAlgorithmDFAInferringMinisat
#ifdef __cplusplus
extern "C" {
#endif
#undef de_libalf_jni_JNIAlgorithmDFAInferringMinisat_serialVersionUID
#define de_libalf_jni_JNIAlgorithmDFAInferringMinisat_serialVersionUID 1LL
#undef de_libalf_jni_JNIAlgorithmDFAInferringMinisat_serialVersionUID
#define de_libalf_jni_JNIAlgorithmDFAInferringMinisat_serialVersionUID 2LL
#undef de_libalf_jni_JNIAlgorithmDFAInferringMinisat_serialVersionUID
#define de_libalf_jni_JNIAlgorithmDFAInferringMinisat_serialVersionUID 2LL
/*
 * Class:     de_libalf_jni_JNIAlgorithmDFAInferringMinisat
 * Method:    init
 * Signature: (JJIZ)J
 */
JNIEXPORT jlong JNICALL Java_de_libalf_jni_JNIAlgorithmDFAInferringMinisat_init__JJIZ
  (JNIEnv *, jobject, jlong, jlong, jint, jboolean);

/*
 * Class:     de_libalf_jni_JNIAlgorithmDFAInferringMinisat
 * Method:    init
 * Signature: (JIZ)J
 */
JNIEXPORT jlong JNICALL Java_de_libalf_jni_JNIAlgorithmDFAInferringMinisat_init__JIZ
  (JNIEnv *, jobject, jlong, jint, jboolean);

/*
 * Class:     de_libalf_jni_JNIAlgorithmDFAInferringMinisat
 * Method:    uses_symmetry_breaking
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_de_libalf_jni_JNIAlgorithmDFAInferringMinisat_uses_1symmetry_1breaking
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_libalf_jni_JNIAlgorithmDFAInferringMinisat
 * Method:    set_symmetry_breaking
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_de_libalf_jni_JNIAlgorithmDFAInferringMinisat_set_1symmetry_1breaking
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     de_libalf_jni_JNIAlgorithmDFAInferringMinisat
 * Method:    is_logging_model
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_de_libalf_jni_JNIAlgorithmDFAInferringMinisat_is_1logging_1model
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_libalf_jni_JNIAlgorithmDFAInferringMinisat
 * Method:    set_log_model
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_de_libalf_jni_JNIAlgorithmDFAInferringMinisat_set_1log_1model
  (JNIEnv *, jobject, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
