# $Id$
# libalf Makefile

.PHONY: all clean angluin_simple_observationtable amore_serialization

all: angluin_simple_observationtable amore_serialization

angluin_simple_observationtable:
	make -C angluin_simple_observationtable

amore_serialization:
	make -C amore_serialization

clean:
	make -C angluin_simple_observationtable clean
	make -C amore_serialization clean

