/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_libalf_jni_BufferedLogger */

#ifndef _Included_de_libalf_jni_BufferedLogger
#define _Included_de_libalf_jni_BufferedLogger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_libalf_jni_BufferedLogger
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_libalf_jni_BufferedLogger_init__
  (JNIEnv *, jobject);

/*
 * Class:     de_libalf_jni_BufferedLogger
 * Method:    init
 * Signature: (IZ)J
 */
JNIEXPORT jlong JNICALL Java_de_libalf_jni_BufferedLogger_init__IZ
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     de_libalf_jni_BufferedLogger
 * Method:    receive_and_flush
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_libalf_jni_BufferedLogger_receive_1and_1flush
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
