# $Id$
# Makefile for libalf interfaces

.PHONY: all clean install uninstall

all:
	+make -C dispatcher all
	+make -C jalf all

clean:
	+make -C dispatcher clean
	+make -C jalf clean

install:
	+make -C dispatcher install

uninstall:
	+make -C dispatcher uninstall


