# $Id$
# LanguageGenerator testsuite Makefile

.PHONY: all clean DFArandomgenerator

all: DFArandomgenerator

DFArandomgenerator:
	make -C DFArandomgenerator

clean:
	make -C DFArandomgenerator clean
