# $Id$
# LanguageGenerator testsuite Makefile

.PHONY: all clean DFArandomgenerator regex_randomgenerator

all: DFArandomgenerator regex_randomgenerator

DFArandomgenerator:
	make -C DFArandomgenerator

regex_randomgenerator:
	make -C regex_randomgenerator

clean:
	make -C DFArandomgenerator clean
	make -C regex_randomgenerator clean
