# $Id$
# regex testsuite Makefile

.PHONY: all clean

PREFIX ?= /usr/local

CPPFLAGS+=-I../../include -I${PREFIX}/include -Wall -ggdb3

LDFLAGS+=-L../../src -L${PREFIX}/lib -lAMoRE++

all: regex_stuff

regex_stuff: regex_stuff

clean:
	-rm regex_stuff

