package de.libalf.dispatcher;

enum DispatcherConstants implements Sendable {
	// enum command_error_code
	ERR_SUCCESS(0),
	ERR_NO_OBJECT(1),
	ERR_BAD_OBJECT(2),

	ERR_BAD_COMMAND(10),
	ERR_NOT_IMPLEMENTED(11),

	ERR_BAD_PARAMETER_COUNT(15),
	ERR_BAD_PARAMETERS(16),

	ERR_COMMAND_FAILED(20),

	ERR_UNRESOLVED_REFERENCES_REMOVED(40),
	ERR_REMAINING_OBJECTS(41),

	ERR_AUTHENTICATION_REQUIRED(100),
	ERR_AUTHENTICATION_FAILED(101),

	ERR_TLS_REQUIRED(110),

	ERR_OUT_OF_MEM(1000),
	ERR_INTERNAL_ERROR(1001),

	// enum client_command
	CLCMD_REQ_CAPA(0),
	CLCMD_REQ_VERSION(1),

	CLCMD_DISCONNECT(10),
	CLCMD_STARTTLS(11),
	CLCMD_AUTH(12),

	CLCMD_CREATE_OBJECT(20),
	CLCMD_DELETE_OBJECT(21),
	CLCMD_GET_OBJECTTYPE(22),
	CLCMD_OBJECT_COMMAND(23),
	CLCMD_COUNT_DISPATCHER_REFERENCES(30),
	/*
	 * CLCMD_ENABLE_CLIENT_REFERENCING(35),
	 * CLCMD_DISABLE_CLIENT_REFERENCING(36), CLCMD_COUNT_CLIENT_REFERENCES(37),
	 * CLCMD_INCREASE_CLIENT_REFERENCES(38),
	 * CLCMD_DECREASE_CLIENT_REFERENCES(39),
	 */

	CLCMD_HELLO_CARSTEN(99),

	// reserved for extensions: >( 1000

	// enum object_type
	OBJ_NONE(-1),
	OBJ_LOGGER(0),
	OBJ_KNOWLEDGEBASE(10),
	OBJ_KNOWLEDGEBASE_ITERATOR(11),
	OBJ_LEARNING_ALGORITHM(20),
	OBJ_NORMALIZER(21),

	// enum logger_command
	LOGGER_RECEIVE_AND_FLUSH(0),
	LOGGER_SET_MIN_LOGLEVEL(1),
	LOGGER_LOG_ALGORITHM(2),
	LOGGER_NOT_LOG_ALGORITHM(3),

	// enum knowledgebase_command
	KNOWLEDGEBASE_SERIALIZE(0),
	KNOWLEDGEBASE_DESERIALIZE(1),
	KNOWLEDGEBASE_TO_DOTFILE(2),
	KNOWLEDGEBASE_TO_STRING(3),

	KNOWLEDGEBASE_IS_ANSWERED(10),
	KNOWLEDGEBASE_IS_EMPTY(11),
	KNOWLEDGEBASE_GET_ALPHABET_SIZE(12),
	KNOWLEDGEBASE_COUNT_QUERIES(13),
	KNOWLEDGEBASE_COUNT_ANSWERS(14),
	KNOWLEDGEBASE_COUNT_RESOLVED_QUERIES(15),
	KNOWLEDGEBASE_GET_MEMORY_USAGE(16),

	KNOWLEDGEBASE_RESOLVE_QUERY(20),
	KNOWLEDGEBASE_RESOLVE_OR_ADD_QUERY(21),
	KNOWLEDGEBASE_ADD_KNOWLEDGE(22),

	KNOWLEDGEBASE_GET_QUERY_TREE(25),
	KNOWLEDGEBASE_MERGE_TREE(26),

	// iterator:
	KNOWLEDGEBASE_BEGIN(30),
	KNOWLEDGEBASE_END(31),
	KNOWLEDGEBASE_QBEGIN(32),
	KNOWLEDGEBASE_QEND(33),

	KNOWLEDGEBASE_CLEAR(40),
	KNOWLEDGEBASE_CLEAR_QUERIES(41),

	KNOWLEDGEBASE_UNDO(50),

	// enum knowledgebase_iterator_command
	KITERATOR_IS_VALID(0),
	KITERATOR_ASSIGN(1),
	KITERATOR_COMPARE(2),

	KITERATOR_NEXT(10),

	KITERATOR_GET_WORD(20),
	KITERATOR_IS_ANSWERED(21),
	KITERATOR_GET_ANSWER(22),
	KITERATOR_ANSWER(23),

	// enum algorithm_command
	LEARNING_ALGORITHM_SERIALIZE(0),
	LEARNING_ALGORITHM_DESERIALIZE(1),
	LEARNING_ALGORITHM_TO_STRING(2),
	LEARNING_ALGORITHM_DESERIALIZE_MAGIC(3),

	LEARNING_ALGORITHM_ASSOCIATE_LOGGER(10),
	LEARNING_ALGORITHM_REMOVE_LOGGER(11),
	LEARNING_ALGORITHM_SET_KNOWLEDGE_SOURCE(12),
	LEARNING_ALGORITHM_GET_KNOWLEDGE_SOURCE(13),
	LEARNING_ALGORITHM_SET_NORMALIZER(14),
	LEARNING_ALGORITHM_GET_NORMALIZER(15),
	LEARNING_ALGORITHM_UNSET_NORMALIZER(16),

	LEARNING_ALGORITHM_GET_MEMORY_STATISTICS(20),
	LEARNING_ALGORITHM_GET_TIMING_STATISTICS(21),
	LEARNING_ALGORITHM_ENABLE_TIMING(22),
	LEARNING_ALGORITHM_DISABLE_TIMING(23),
	LEARNING_ALGORITHM_RESET_TIMING(24),

	LEARNING_ALGORITHM_GET_ALPHABET_SIZE(30),
	LEARNING_ALGORITHM_INCREASE_ALPHABET_SIZE(31),

	LEARNING_ALGORITHM_CONJECTURE_READY(40),
	LEARNING_ALGORITHM_ADVANCE(41),
	LEARNING_ALGORITHM_ADD_COUNTEREXAMPLE(42),

	LEARNING_ALGORITHM_SUPPORTS_SYNC(50),
	LEARNING_ALGORITHM_SYNC_TO_KNOWLEDGEBASE(51),

	// enum normalizer_command
	NORMALIZER_SERIALIZE(0),
	NORMALIZER_DESERIALIZE(1),
	NORMALIZER_DESERIALIZE_EXTENSION(2),

	NORMALIZER_GET_TYPE(10),

	NORMALIZER_NORMALIZE_A_WORD_PNF(20),
	NORMALIZER_NORMALIZE_A_WORD_SNF(21),

	;

	static final int DISPATCHER_PROTOCOL_VERSION = 1;

	static final int DISPATCHER_DEFAULT_PORT = 24940;

	final int id;

	private DispatcherConstants(int id) {
		this.id = id;
	}

	@Override
	public int getInt() {
		return this.id;
	}

	DispatcherProtocolException getException() {
		return getException(null);
	}

	DispatcherProtocolException getException(Throwable cause) {
		return new DispatcherProtocolException(toString(), cause);
	}

	static String getErrorString(int code) {
		DispatcherConstants error = getError(code);
		return code + " (0x" + printUInt32(code) + ")" + (error == null ? "" : " " + error);
	}

	static String printUInt32(int code) {
		return String.format("%08X", code);
	}

	private static DispatcherConstants getError(int code) {
		for (DispatcherConstants c : DispatcherConstants.values())
			if (c.id == code && c.toString().startsWith("ERR_"))
				return c;
		return null;
	}
}
