/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_libalf_jni_JNIObject */

#ifndef _Included_de_libalf_jni_JNIObject
#define _Included_de_libalf_jni_JNIObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_libalf_jni_JNIObject
 * Method:    getLibALFVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_libalf_jni_JNIObject_getLibALFVersion
  (JNIEnv *, jclass);

/*
 * Class:     de_libalf_jni_JNIObject
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_libalf_jni_JNIObject_destroy
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
