/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_libalf_jni_JNIAlgorithmKearnsVazirani */

#ifndef _Included_de_libalf_jni_JNIAlgorithmKearnsVazirani
#define _Included_de_libalf_jni_JNIAlgorithmKearnsVazirani
#ifdef __cplusplus
extern "C" {
#endif
#undef de_libalf_jni_JNIAlgorithmKearnsVazirani_serialVersionUID
#define de_libalf_jni_JNIAlgorithmKearnsVazirani_serialVersionUID 1LL
#undef de_libalf_jni_JNIAlgorithmKearnsVazirani_serialVersionUID
#define de_libalf_jni_JNIAlgorithmKearnsVazirani_serialVersionUID 2LL
#undef de_libalf_jni_JNIAlgorithmKearnsVazirani_serialVersionUID
#define de_libalf_jni_JNIAlgorithmKearnsVazirani_serialVersionUID 2LL
/*
 * Class:     de_libalf_jni_JNIAlgorithmKearnsVazirani
 * Method:    init
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_de_libalf_jni_JNIAlgorithmKearnsVazirani_init__JI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     de_libalf_jni_JNIAlgorithmKearnsVazirani
 * Method:    init
 * Signature: (JIJ)J
 */
JNIEXPORT jlong JNICALL Java_de_libalf_jni_JNIAlgorithmKearnsVazirani_init__JIJ
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     de_libalf_jni_JNIAlgorithmKearnsVazirani
 * Method:    init
 * Signature: (JIZ)J
 */
JNIEXPORT jlong JNICALL Java_de_libalf_jni_JNIAlgorithmKearnsVazirani_init__JIZ
  (JNIEnv *, jobject, jlong, jint, jboolean);

/*
 * Class:     de_libalf_jni_JNIAlgorithmKearnsVazirani
 * Method:    init
 * Signature: (JIJZ)J
 */
JNIEXPORT jlong JNICALL Java_de_libalf_jni_JNIAlgorithmKearnsVazirani_init__JIJZ
  (JNIEnv *, jobject, jlong, jint, jlong, jboolean);

/*
 * Class:     de_libalf_jni_JNIAlgorithmKearnsVazirani
 * Method:    get_inner_node_count
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_libalf_jni_JNIAlgorithmKearnsVazirani_get_1inner_1node_1count
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_libalf_jni_JNIAlgorithmKearnsVazirani
 * Method:    get_leaf_node_count
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_libalf_jni_JNIAlgorithmKearnsVazirani_get_1leaf_1node_1count
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_libalf_jni_JNIAlgorithmKearnsVazirani
 * Method:    uses_binary_search
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_de_libalf_jni_JNIAlgorithmKearnsVazirani_uses_1binary_1search
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_libalf_jni_JNIAlgorithmKearnsVazirani
 * Method:    set_binary_search
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_de_libalf_jni_JNIAlgorithmKearnsVazirani_set_1binary_1search
  (JNIEnv *, jobject, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
