/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_libalf_jni_JNIAlgorithmCounterexampleLearning */

#ifndef _Included_de_libalf_jni_JNIAlgorithmCounterexampleLearning
#define _Included_de_libalf_jni_JNIAlgorithmCounterexampleLearning
#ifdef __cplusplus
extern "C" {
#endif
#undef de_libalf_jni_JNIAlgorithmCounterexampleLearning_serialVersionUID
#define de_libalf_jni_JNIAlgorithmCounterexampleLearning_serialVersionUID 1LL
#undef de_libalf_jni_JNIAlgorithmCounterexampleLearning_serialVersionUID
#define de_libalf_jni_JNIAlgorithmCounterexampleLearning_serialVersionUID 2LL
#undef de_libalf_jni_JNIAlgorithmCounterexampleLearning_serialVersionUID
#define de_libalf_jni_JNIAlgorithmCounterexampleLearning_serialVersionUID 2LL
/*
 * Class:     de_libalf_jni_JNIAlgorithmCounterexampleLearning
 * Method:    init
 * Signature: (JJIJ)J
 */
JNIEXPORT jlong JNICALL Java_de_libalf_jni_JNIAlgorithmCounterexampleLearning_init__JJIJ
  (JNIEnv *, jobject, jlong, jlong, jint, jlong);

/*
 * Class:     de_libalf_jni_JNIAlgorithmCounterexampleLearning
 * Method:    init
 * Signature: (JIJ)J
 */
JNIEXPORT jlong JNICALL Java_de_libalf_jni_JNIAlgorithmCounterexampleLearning_init__JIJ
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     de_libalf_jni_JNIAlgorithmCounterexampleLearning
 * Method:    derive_conjecture
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_libalf_jni_JNIAlgorithmCounterexampleLearning_derive_1conjecture
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
