/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_libalf_jni_JNIAlgorithmBiermannOriginal */

#ifndef _Included_de_libalf_jni_JNIAlgorithmBiermannOriginal
#define _Included_de_libalf_jni_JNIAlgorithmBiermannOriginal
#ifdef __cplusplus
extern "C" {
#endif
#undef de_libalf_jni_JNIAlgorithmBiermannOriginal_serialVersionUID
#define de_libalf_jni_JNIAlgorithmBiermannOriginal_serialVersionUID 1LL
#undef de_libalf_jni_JNIAlgorithmBiermannOriginal_serialVersionUID
#define de_libalf_jni_JNIAlgorithmBiermannOriginal_serialVersionUID 2LL
#undef de_libalf_jni_JNIAlgorithmBiermannOriginal_serialVersionUID
#define de_libalf_jni_JNIAlgorithmBiermannOriginal_serialVersionUID 1LL
#undef de_libalf_jni_JNIAlgorithmBiermannOriginal_serialVersionUID
#define de_libalf_jni_JNIAlgorithmBiermannOriginal_serialVersionUID 1LL
/*
 * Class:     de_libalf_jni_JNIAlgorithmBiermannOriginal
 * Method:    init
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_de_libalf_jni_JNIAlgorithmBiermannOriginal_init__JII
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     de_libalf_jni_JNIAlgorithmBiermannOriginal
 * Method:    init
 * Signature: (JIJI)J
 */
JNIEXPORT jlong JNICALL Java_de_libalf_jni_JNIAlgorithmBiermannOriginal_init__JIJI
  (JNIEnv *, jobject, jlong, jint, jlong, jint);

/*
 * Class:     de_libalf_jni_JNIAlgorithmBiermannOriginal
 * Method:    get_nondeterminism
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_libalf_jni_JNIAlgorithmBiermannOriginal_get_1nondeterminism
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
