/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_libalf_jni_JNIAlgorithmDFAInferringZ3 */

#ifndef _Included_de_libalf_jni_JNIAlgorithmDFAInferringZ3
#define _Included_de_libalf_jni_JNIAlgorithmDFAInferringZ3
#ifdef __cplusplus
extern "C" {
#endif
#undef de_libalf_jni_JNIAlgorithmDFAInferringZ3_serialVersionUID
#define de_libalf_jni_JNIAlgorithmDFAInferringZ3_serialVersionUID 1LL
#undef de_libalf_jni_JNIAlgorithmDFAInferringZ3_serialVersionUID
#define de_libalf_jni_JNIAlgorithmDFAInferringZ3_serialVersionUID 2LL
#undef de_libalf_jni_JNIAlgorithmDFAInferringZ3_serialVersionUID
#define de_libalf_jni_JNIAlgorithmDFAInferringZ3_serialVersionUID 2LL
/*
 * Class:     de_libalf_jni_JNIAlgorithmDFAInferringZ3
 * Method:    init
 * Signature: (JJIZZ)J
 */
JNIEXPORT jlong JNICALL Java_de_libalf_jni_JNIAlgorithmDFAInferringZ3_init__JJIZZ
  (JNIEnv *, jobject, jlong, jlong, jint, jboolean, jboolean);

/*
 * Class:     de_libalf_jni_JNIAlgorithmDFAInferringZ3
 * Method:    init
 * Signature: (JIZZ)J
 */
JNIEXPORT jlong JNICALL Java_de_libalf_jni_JNIAlgorithmDFAInferringZ3_init__JIZZ
  (JNIEnv *, jobject, jlong, jint, jboolean, jboolean);

/*
 * Class:     de_libalf_jni_JNIAlgorithmDFAInferringZ3
 * Method:    is_using_variables
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_de_libalf_jni_JNIAlgorithmDFAInferringZ3_is_1using_1variables
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_libalf_jni_JNIAlgorithmDFAInferringZ3
 * Method:    set_using_variables
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_de_libalf_jni_JNIAlgorithmDFAInferringZ3_set_1using_1variables
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     de_libalf_jni_JNIAlgorithmDFAInferringZ3
 * Method:    is_using_enum
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_de_libalf_jni_JNIAlgorithmDFAInferringZ3_is_1using_1enum
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_libalf_jni_JNIAlgorithmDFAInferringZ3
 * Method:    set_using_enum
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_de_libalf_jni_JNIAlgorithmDFAInferringZ3_set_1using_1enum
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     de_libalf_jni_JNIAlgorithmDFAInferringZ3
 * Method:    is_logging_model
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_de_libalf_jni_JNIAlgorithmDFAInferringZ3_is_1logging_1model
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_libalf_jni_JNIAlgorithmDFAInferringZ3
 * Method:    set_log_model
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_de_libalf_jni_JNIAlgorithmDFAInferringZ3_set_1log_1model
  (JNIEnv *, jobject, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
