/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_libalf_jni_JNIAlgorithmBiermannMiniSAT */

#ifndef _Included_de_libalf_jni_JNIAlgorithmBiermannMiniSAT
#define _Included_de_libalf_jni_JNIAlgorithmBiermannMiniSAT
#ifdef __cplusplus
extern "C" {
#endif
#undef de_libalf_jni_JNIAlgorithmBiermannMiniSAT_serialVersionUID
#define de_libalf_jni_JNIAlgorithmBiermannMiniSAT_serialVersionUID 2LL
#undef de_libalf_jni_JNIAlgorithmBiermannMiniSAT_serialVersionUID
#define de_libalf_jni_JNIAlgorithmBiermannMiniSAT_serialVersionUID 2LL
/*
 * Class:     de_libalf_jni_JNIAlgorithmBiermannMiniSAT
 * Method:    init
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_de_libalf_jni_JNIAlgorithmBiermannMiniSAT_init__JI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     de_libalf_jni_JNIAlgorithmBiermannMiniSAT
 * Method:    init
 * Signature: (JIJ)J
 */
JNIEXPORT jlong JNICALL Java_de_libalf_jni_JNIAlgorithmBiermannMiniSAT_init__JIJ
  (JNIEnv *, jobject, jlong, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
