/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_libalf_jni_JNIBufferedLogger */

#ifndef _Included_de_libalf_jni_JNIBufferedLogger
#define _Included_de_libalf_jni_JNIBufferedLogger
#ifdef __cplusplus
extern "C" {
#endif
#undef de_libalf_jni_JNIBufferedLogger_serialVersionUID
#define de_libalf_jni_JNIBufferedLogger_serialVersionUID 2LL
#undef de_libalf_jni_JNIBufferedLogger_ERROR
#define de_libalf_jni_JNIBufferedLogger_ERROR 1L
#undef de_libalf_jni_JNIBufferedLogger_WARN
#define de_libalf_jni_JNIBufferedLogger_WARN 2L
#undef de_libalf_jni_JNIBufferedLogger_INFO
#define de_libalf_jni_JNIBufferedLogger_INFO 3L
#undef de_libalf_jni_JNIBufferedLogger_DEBUG
#define de_libalf_jni_JNIBufferedLogger_DEBUG 4L
/*
 * Class:     de_libalf_jni_JNIBufferedLogger
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_libalf_jni_JNIBufferedLogger_init__
  (JNIEnv *, jobject);

/*
 * Class:     de_libalf_jni_JNIBufferedLogger
 * Method:    init
 * Signature: (IZ)J
 */
JNIEXPORT jlong JNICALL Java_de_libalf_jni_JNIBufferedLogger_init__IZ
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     de_libalf_jni_JNIBufferedLogger
 * Method:    receive_and_flush
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_libalf_jni_JNIBufferedLogger_receive_1and_1flush
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
