/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_libalf_jni_JNIAlgorithmDeLeTe2 */

#ifndef _Included_de_libalf_jni_JNIAlgorithmDeLeTe2
#define _Included_de_libalf_jni_JNIAlgorithmDeLeTe2
#ifdef __cplusplus
extern "C" {
#endif
#undef de_libalf_jni_JNIAlgorithmDeLeTe2_serialVersionUID
#define de_libalf_jni_JNIAlgorithmDeLeTe2_serialVersionUID 1LL
#undef de_libalf_jni_JNIAlgorithmDeLeTe2_serialVersionUID
#define de_libalf_jni_JNIAlgorithmDeLeTe2_serialVersionUID 2LL
#undef de_libalf_jni_JNIAlgorithmDeLeTe2_serialVersionUID
#define de_libalf_jni_JNIAlgorithmDeLeTe2_serialVersionUID 1LL
/*
 * Class:     de_libalf_jni_JNIAlgorithmDeLeTe2
 * Method:    init
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_de_libalf_jni_JNIAlgorithmDeLeTe2_init__JI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     de_libalf_jni_JNIAlgorithmDeLeTe2
 * Method:    init
 * Signature: (JIJ)J
 */
JNIEXPORT jlong JNICALL Java_de_libalf_jni_JNIAlgorithmDeLeTe2_init__JIJ
  (JNIEnv *, jobject, jlong, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
