# $Id$
# libalf-interfaces testsuite Makefile

.PHONY: all clean  biermann_original

all: biermann_original


biermann_original:
	+make -C biermann_original


clean:
	make -C biermann_original clean

